// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Exercise struct {
	ID        int64 `json:"id"`
	WorkoutID int64 `json:"workout_id"`
	// The body section this exercise hits - chest, back, etc.
	Type string `json:"type"`
	// What is the exercise called?
	Title string `json:"title"`
	// description of the exercies - good for reminders
	Desc sql.NullString `json:"desc"`
	// tracks what the overall volume was the last time this exercise was performed
	LastVolume int64 `json:"last_volume"`
}

type Set struct {
	ID         int64         `json:"id"`
	ExerciseID int64         `json:"exercise_id"`
	Reps       sql.NullInt64 `json:"reps"`
	Weight     sql.NullInt64 `json:"weight"`
	// tracks what the overall volume was the last time this exercise was performed
	LastVolume int64 `json:"last_volume"`
}

type User struct {
	ID int64 `json:"id"`
	// email to sign in - also to send reminders
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Username  string       `json:"username"`
	CreatedAt time.Time    `json:"created_at"`
	Birthday  sql.NullTime `json:"birthday"`
}

type Workout struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Title  string `json:"title"`
	// Description of workout
	Body string `json:"body"`
	// Timestamp of the last time completed
	LastTime time.Time `json:"last_time"`
}
