# found on https://github.com/sqlfluff/sqlfluff-github-actions/tree/main/menu_of_workflows/sunrise_movement , edited to current sqlfluff workflow
name: Lint SQL

on: [pull_request]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./backend/db/query
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.8"
      - name: Install SQLFluff
        run: "pip install sqlfluff"
      - name: Lint Queries
        run: "sqlfluff lint ./"